language: scala

dist: xenial

jdk: openjdk8

scala:
   - 2.12.8

services:
  - docker

env:
  - PATH="${PATH}:/home/travis/.local/share/coursier/bin"

before_install:
    - command -V docker
    - cd $(mktemp -d) && curl -fLo ./coursier https://git.io/coursier-cli-linux && chmod +x ./coursier && sudo mv ./coursier /usr/local/bin/coursier && cd -
    - coursier install scalafmt
    - command -V scalafmt
    - sudo apt-get update && sudo apt-get install --yes parallel

script:
    - make docker_build
    - make docker_test

# vim: set filetype=yaml fileformat=unix nowrap:
