language: scala

dist: xenial

jdk: openjdk8

scala:
   - 2.12.8

env:
  - PATH="${PATH}:/home/travis/.local/share/coursier/bin"

script:
    - make docker_build
    - make docker_test

after_success:
  - export CODECOV_TOKEN="9837f692-ffac-46db-bc8e-01ef3b9b5b3c"
  - bash <(curl -s https://codecov.io/bash)

# vim: set filetype=yaml fileformat=unix nowrap:
